const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {Archive}=require('./dist/archive');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'sop-test-')); const a=new Archive(root,path.join(root,'state')); fs.mkdirSync(a.pending,{recursive:true});fs.mkdirSync(path.join(a.raw,'分類','子分類'),{recursive:true});return a;}
function add(a,name='a.txt'){const p=path.join(a.pending,name);fs.writeFileSync(p,'content');fs.utimesSync(p,1,1);return {fileName:name,category:'分類/子分類',reason:'test',evidence:'read content',expectedFingerprint:a.snapshot(p).fingerprint};}
test('move, hash, journal and repeat',()=>{const a=fixture(),d=add(a);assert.equal(a.batch([d],true).results[0].status,'preview');assert.equal(a.batch([d]).results[0].status,'success');assert.equal(fs.readFileSync(path.join(a.raw,d.category,d.fileName),'utf8'),'content');assert.equal(a.batch([d]).results[0].status,'error');assert.match(fs.readFileSync(path.join(a.state,'journal.jsonl'),'utf8'),/success/);});
test('conflict never overwrites',()=>{const a=fixture(),d=add(a);fs.writeFileSync(path.join(a.raw,d.category,d.fileName),'original');assert.equal(a.batch([d]).results[0].status,'error');assert.equal(fs.readFileSync(path.join(a.raw,d.category,d.fileName),'utf8'),'original');assert.ok(fs.existsSync(path.join(a.pending,d.fileName)));});
test('traversal and missing category rejected',()=>{for(const category of ['../escape','!待整理','分類/../子分類','missing']){const a=fixture(),d=add(a);assert.equal(a.batch([{...d,category}]).results[0].status,'error');}});
test('recent and stale fingerprint rejected',()=>{const a=fixture(),d=add(a);fs.writeFileSync(path.join(a.pending,d.fileName),'new');assert.equal(a.list().items[0].status,'hold');assert.equal(a.batch([d]).results[0].status,'error');fs.utimesSync(path.join(a.pending,d.fileName),1,1);assert.equal(a.batch([d]).results[0].status,'error');});
test('unreadable item is held in place',()=>{const a=fixture(),d=add(a,'blocked.txt'),blocked=path.resolve(path.join(a.pending,d.fileName)),originalRead=fs.readFileSync;fs.readFileSync=(target,...args)=>{if(path.resolve(String(target))===blocked){const error=new Error('EACCES: permission denied');error.code='EACCES';throw error;}return originalRead.call(fs,target,...args);};try{const item=a.list().items.find(item=>item.fileName===d.fileName);assert.equal(item.status,'hold');assert.match(item.reason,/EACCES|permission denied/);assert.ok(fs.existsSync(blocked));}finally{fs.readFileSync=originalRead;}});
test('folder kept intact',()=>{const a=fixture();const p=path.join(a.pending,'bundle');fs.mkdirSync(p);fs.writeFileSync(path.join(p,'attachment.txt'),'content');fs.utimesSync(path.join(p,'attachment.txt'),1,1);fs.utimesSync(p,1,1);const d={fileName:'bundle',category:'分類',reason:'same subject',evidence:'attachment read',expectedFingerprint:a.snapshot(p).fingerprint};assert.equal(a.batch([d]).results[0].status,'success');assert.ok(fs.existsSync(path.join(a.raw,'分類','bundle','attachment.txt')));});
test('run lock, hold dedup, confirmation state, read-only list',()=>{const a=fixture();const d=add(a);const hold={...d,action:'hold',reason:'cannot read content'};assert.equal(a.batch([hold]).changed,true);assert.equal(a.batch([hold]).changed,false);assert.equal(a.list().items[0].status,'waiting_confirmation');fs.writeFileSync(path.join(a.state,'run.lock'),'locked');assert.throws(()=>a.batch([d]),/EEXIST/);const b=new Archive(path.join(a.root,'missing'));assert.throws(()=>b.list());assert.equal(fs.existsSync(b.pending),false);});
test('MCP handshake exposes the current H-drive database',async()=>{const {Client}=require('@modelcontextprotocol/sdk/client/index.js');const {StdioClientTransport}=require('@modelcontextprotocol/sdk/client/stdio.js');const client=new Client({name:'archive-test',version:'1.0.0'});try{await client.connect(new StdioClientTransport({command:process.execPath,args:[path.join(__dirname,'dist','index.js')]}));const tools=await client.listTools();assert.ok(tools.tools.some(t=>t.name==='organize_sop_batch'));const reply=await client.callTool({name:'list_pending_sop_files',arguments:{}});const body=JSON.parse(reply.content[0].text);assert.equal(body.databaseRoot,path.resolve(__dirname,'..'));}finally{await client.close();}});
